minecraft_version=26.3
loader_version=0.19.3
loom_version=1.17.13
loom_plugin_id=net.fabricmc.fabric-loom
fabric_api_version=0.162.0+26.3
java_version=25
minecraft_dependency=~26.3
compat_source_set=mc263
use_mojang_mappings=false
mod_dependency_configuration=implementation
