minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.13
loom_plugin_id=net.fabricmc.fabric-loom
fabric_api_version=0.154.0+26.2
java_version=25
minecraft_dependency=~26.2
compat_source_set=mc262
use_mojang_mappings=false
mod_dependency_configuration=implementation
